[book]
title        = "FIFA 11+（裁判员版）"
authors      = ["FIFA"]
language     = "zh"
multilingual = false
src = "src"

[output.html]
mathjax-support = true
git-repository-url = "https://zzzxj12138.github.io/index/"